dataset:
  target: dataset.licdataset.LICDataset
  params:
    # Path to the file list.
    file_list: ./datalists/train.list
    out_size: 512
    crop_type: random
    use_hflip: True
    use_rot: False

data_loader:
  batch_size: 4
  shuffle: true
  num_workers: 8
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
